package codes.yousef.aether.core.security

import codes.yousef.aether.core.Exchange
import codes.yousef.aether.core.pipeline.Middleware

/** A nonce or SHA-256/384/512 source generated by the actual application shell build. */
class CspDynamicSource private constructor(internal val directive: String) {
    override fun toString(): String = directive

    companion object {
        fun nonce(base64Value: String): CspDynamicSource {
            requireBase64Token(base64Value)
            return CspDynamicSource("'nonce-$base64Value'")
        }

        fun sha256(base64Value: String): CspDynamicSource = hash("sha256", base64Value)
        fun sha384(base64Value: String): CspDynamicSource = hash("sha384", base64Value)
        fun sha512(base64Value: String): CspDynamicSource = hash("sha512", base64Value)

        private fun hash(algorithm: String, value: String): CspDynamicSource {
            requireBase64Token(value)
            return CspDynamicSource("'$algorithm-$value'")
        }
    }
}

fun interface PrivateCspSourceProvider {
    suspend fun sources(exchange: Exchange): Set<CspDynamicSource>
}

data class PrivateSecurityHeadersConfig(
    val hstsMaxAgeSeconds: Long = 31_536_000,
    val hstsIncludeSubDomains: Boolean = true,
    val hstsPreload: Boolean = false,
    val scriptSources: PrivateCspSourceProvider = PrivateCspSourceProvider { emptySet() },
    val styleSources: PrivateCspSourceProvider = PrivateCspSourceProvider { emptySet() }
) {
    init {
        require(hstsMaxAgeSeconds in 0..63_072_000) { "HSTS max age must be 0..63072000 seconds" }
    }
}

/**
 * Headers for authenticated application shells and private APIs. They are installed before `next`,
 * so redirects and safely rendered errors retain the same policy.
 */
class PrivateSecurityHeaders(private val config: PrivateSecurityHeadersConfig = PrivateSecurityHeadersConfig()) {
    fun asMiddleware(): Middleware = { exchange, next ->
        val scriptSources = config.scriptSources.sources(exchange).map { it.directive }.sorted()
        val styleSources = config.styleSources.sources(exchange).map { it.directive }.sorted()
        val csp = buildString {
            append("default-src 'none'; base-uri 'none'; connect-src 'self'; form-action 'self'; ")
            append("frame-ancestors 'none'; img-src 'self' data:; object-src 'none'; ")
            append("script-src 'self'")
            scriptSources.forEach { append(' ').append(it) }
            append("; style-src 'self'")
            styleSources.forEach { append(' ').append(it) }
            append(';')
        }
        val hsts = buildString {
            append("max-age=").append(config.hstsMaxAgeSeconds)
            if (config.hstsIncludeSubDomains) append("; includeSubDomains")
            if (config.hstsPreload) append("; preload")
        }
        exchange.response.setHeader("Cache-Control", "no-store")
        exchange.response.setHeader("Pragma", "no-cache")
        exchange.response.setHeader("Content-Security-Policy", csp)
        exchange.response.setHeader("Strict-Transport-Security", hsts)
        exchange.response.setHeader("X-Content-Type-Options", "nosniff")
        exchange.response.setHeader("X-Frame-Options", "DENY")
        exchange.response.setHeader("Referrer-Policy", "no-referrer")
        exchange.response.setHeader("Permissions-Policy", "camera=(), microphone=(), geolocation=()")
        exchange.response.setHeader("Cross-Origin-Opener-Policy", "same-origin")
        exchange.response.setHeader("Cross-Origin-Resource-Policy", "same-origin")
        exchange.response.setHeader("X-Permitted-Cross-Domain-Policies", "none")
        next()
    }
}


data class PublicCacheHeadersConfig(
    val maxAgeSeconds: Long,
    val sharedMaxAgeSeconds: Long? = null,
    val immutable: Boolean = false
) {
    init {
        require(maxAgeSeconds in 0..31_536_000) { "Public max age must be 0..31536000 seconds" }
        require(sharedMaxAgeSeconds == null || sharedMaxAgeSeconds in 0..31_536_000) {
            "Shared max age must be 0..31536000 seconds"
        }
    }
}

/** Explicit profile for non-sensitive public assets; never install it on authenticated routes. */
class PublicCacheHeaders(private val config: PublicCacheHeadersConfig) {
    fun asMiddleware(): Middleware = { exchange, next ->
        val policy = buildString {
            append("public, max-age=").append(config.maxAgeSeconds)
            config.sharedMaxAgeSeconds?.let { append(", s-maxage=").append(it) }
            if (config.immutable) append(", immutable")
        }
        exchange.response.setHeader("Cache-Control", policy)
        next()
    }
}

private val BASE64_TOKEN = Regex("[A-Za-z0-9+/=_-]{16,256}")
private fun requireBase64Token(value: String) {
    require(BASE64_TOKEN.matches(value)) { "CSP nonce or hash must be a bounded base64 token" }
}
